# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: kir-annotator tests

on:
  push:
    branches: [ "master", "feature-github-actions" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  run-tests:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
        
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.9
        use-mamba: true
        environment-file: kir-annotator-env.yml
        activate-environment: kir-annotator-env
    - name: Install the package
      run: pip install .
    - name: Test with Pytest
      run: pytest
